name: Caller Workflow
on:
  push:
    branches:
      - main
      - develop


jobs:
    ## move the secrets to org level , remove from repo level
    call-main:
      if: github.ref == 'refs/heads/main'
      uses: ./.github/workflows/pacs-datahub-ai-deploy-databricks-asset-bundle.yml
      with:
        ENVIRONMENT: prod
        PROJECT_NAME: pacs-743-model-deployment-template_prod
        FOLDER_NAME: /Workspace/Shared/model-deployment-template_prod
        RUNNER: dev-runner
      secrets:
              TOKEN: ${{ secrets.PERSONAL_DEV3_ACCESS_TOKEN }}
              HOST : ${{secrets.DATABRICKS_DEV3_HOST}}
              GIT_TOKEN : ${{secrets.GIT_TOKEN}}

    call-develop:
      if: github.ref == 'refs/heads/develop'
      uses: ./.github/workflows/pacs-datahub-ai-deploy-databricks-asset-bundle.yml
      with:
        ENVIRONMENT: dev
        PROJECT_NAME: pacs-743-model-deployment-template
        FOLDER_NAME: /Workspace/pacs-743-model-deployment-template
        RUNNER: dev-runner
      secrets:
              TOKEN: ${{ secrets.PERSONAL_DEV3_ACCESS_TOKEN }}
              HOST : ${{secrets.DATABRICKS_DEV3_HOST}}
              GIT_TOKEN : ${{secrets.GIT_TOKEN}}
    call-feature:
      if: github.ref == 'refs/heads/feature/ps'
      uses: ./.github/workflows/pacs-datahub-ai-deploy-databricks-asset-bundle.yml
      with:
        ENVIRONMENT: dev
        PROJECT_NAME: pacs-743-model-deployment-template
        FOLDER_NAME: /Workspace/pacs-743-model-deployment-template
        RUNNER: dev-runner
      secrets:
              TOKEN: ${{ secrets.PERSONAL_DEV3_ACCESS_TOKEN }}
              HOST : ${{secrets.DATABRICKS_DEV3_HOST}}
              GIT_TOKEN : ${{secrets.GIT_TOKEN}}